services:
  rl_sar_jazzy:
    image: rl_sar_jazzy
    build:
      context: ..
      dockerfile: rl_sar_jazzy/Dockerfile
    container_name: rl_sar_jazzy
    stop_signal: SIGINT
    network_mode: host
    privileged: true
    stdin_open: true
    #runtime: nvidia
    tty: true
    user: sar
    volumes:
      # - $HOME/jazzy_ws/src:/home/sar/jazzy_ws/src
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - NVIDIA_VISIBLE_DEVICES=all # Makes all NVIDIA devices visible to the container
      - NVIDIA_DRIVER_CAPABILITIES=all # Grants all NVIDIA driver capabilities to the container
      - __NV_PRIME_RENDER_OFFLOAD=1 # Enables NVIDIA PRIME render offload
      - __GLX_VENDOR_LIBRARY_NAME=nvidia # Specifies the GLX vendor library to use (NVIDIA)
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=66
    cap_add:
      - sys_nice
    ulimits:
      rtprio: 99
      memlock: -1
    command: bash
